const {contextBridge,ipcRenderer}=require('electron');
contextBridge.exposeInMainWorld('api',{
  app:{info:()=>ipcRenderer.invoke('app:info')},
  dashboard:{
    resumen:()=>ipcRenderer.invoke('dashboard:resumen'),
    tablero:f=>ipcRenderer.invoke('dashboard:tablero',f)
  },
  configuracion:{obtener:()=>ipcRenderer.invoke('configuracion:obtener'),guardar:d=>ipcRenderer.invoke('configuracion:guardar',d)},
  reportes:{egresos:f=>ipcRenderer.invoke('reportes:egresos',f),combustible:f=>ipcRenderer.invoke('reportes:combustible',f),pdf:(html,nombreSugerido)=>ipcRenderer.invoke('reportes:pdf',{html,nombreSugerido})},
  bitacora:{
    listar:f=>ipcRenderer.invoke('bitacora:listar',f),
    obtener:id=>ipcRenderer.invoke('bitacora:obtener',id),
    guardar:d=>ipcRenderer.invoke('bitacora:guardar',d),
    eliminar:id=>ipcRenderer.invoke('bitacora:eliminar',id),
    resumen:()=>ipcRenderer.invoke('bitacora:resumen')
  },
  vehiculos:{
    listar:f=>ipcRenderer.invoke('vehiculos:listar',f),
    guardar:d=>ipcRenderer.invoke('vehiculos:guardar',d),
    eliminar:id=>ipcRenderer.invoke('vehiculos:eliminar',id)
  },
  conductores:{
    listar:f=>ipcRenderer.invoke('conductores:listar',f),
    guardar:d=>ipcRenderer.invoke('conductores:guardar',d),
    eliminar:id=>ipcRenderer.invoke('conductores:eliminar',id)
  },
  clientes:{
    listar:f=>ipcRenderer.invoke('clientes:listar',f),
    guardar:d=>ipcRenderer.invoke('clientes:guardar',d),
    eliminar:id=>ipcRenderer.invoke('clientes:eliminar',id)
  },
  combustible:{
    listar:f=>ipcRenderer.invoke('combustible:listar',f),
    guardar:d=>ipcRenderer.invoke('combustible:guardar',d),
    eliminar:id=>ipcRenderer.invoke('combustible:eliminar',id),
    resumen:f=>ipcRenderer.invoke('combustible:resumen',f),
    rendimientoVehiculos:()=>ipcRenderer.invoke('combustible:rendimiento_vehiculos')
  },
  empleados:{
    listar:f=>ipcRenderer.invoke('empleados:listar',f),
    resumen:()=>ipcRenderer.invoke('empleados:resumen'),
    guardar:d=>ipcRenderer.invoke('empleados:guardar',d),
    eliminar:id=>ipcRenderer.invoke('empleados:eliminar',id)
  },
  ingresos:{
    listar:f=>ipcRenderer.invoke('ingresos:listar',f),
    guardar:d=>ipcRenderer.invoke('ingresos:guardar',d),
    eliminar:id=>ipcRenderer.invoke('ingresos:eliminar',id),
    resumen:f=>ipcRenderer.invoke('ingresos:resumen',f)
  },
  egresos:{
    listar:f=>ipcRenderer.invoke('egresos:listar',f),
    guardar:d=>ipcRenderer.invoke('egresos:guardar',d),
    eliminar:id=>ipcRenderer.invoke('egresos:eliminar',id),
    resumen:f=>ipcRenderer.invoke('egresos:resumen',f)
  },
  finanzas:{
    categorias:tipo=>ipcRenderer.invoke('finanzas:categorias',{tipo})
  },
  viaticos:{
    listar:f=>ipcRenderer.invoke('viaticos:listar',f),
    viajes_disponibles:f=>ipcRenderer.invoke('viaticos:viajes_disponibles',f),
    guardar:d=>ipcRenderer.invoke('viaticos:guardar',d),
    liquidar:id=>ipcRenderer.invoke('viaticos:liquidar',id),
    eliminar:id=>ipcRenderer.invoke('viaticos:eliminar',id),
    resumen:f=>ipcRenderer.invoke('viaticos:resumen',f)
  },
  planilla:{
    listar:f=>ipcRenderer.invoke('planilla:listar',f),
    obtener:id=>ipcRenderer.invoke('planilla:obtener',id),
    guardar:d=>ipcRenderer.invoke('planilla:guardar',d),
    generar:d=>ipcRenderer.invoke('planilla:generar',d),
    pagar:id=>ipcRenderer.invoke('planilla:pagar',id),
    eliminar:id=>ipcRenderer.invoke('planilla:eliminar',id),
    sugerencia:()=>ipcRenderer.invoke('planilla:sugerencia')
  },
  comisiones:{
    listar:f=>ipcRenderer.invoke('comisiones:listar',f),
    resumen:f=>ipcRenderer.invoke('comisiones:resumen',f),
    guardar:d=>ipcRenderer.invoke('comisiones:guardar',d),
    pagar:d=>ipcRenderer.invoke('comisiones:pagar',d),
    pagarConductor:d=>ipcRenderer.invoke('comisiones:pagar_conductor',d),
    eliminar:id=>ipcRenderer.invoke('comisiones:eliminar',id),
    generar:d=>ipcRenderer.invoke('comisiones:generar',d)
  },
  archivos:{
    guardarImagen:(dataUrl,nombreSugerido)=>ipcRenderer.invoke('archivos:guardar_imagen',{dataUrl,nombreSugerido}),
    guardarImagenes:(archivos,tituloCarpeta)=>ipcRenderer.invoke('archivos:guardar_imagenes',{archivos,tituloCarpeta})
  },
  usuarios:{
    estadoInstalacion:()=>ipcRenderer.invoke('usuarios:estado_instalacion'),
    instalar:d=>ipcRenderer.invoke('usuarios:instalar',d),
    listar:f=>ipcRenderer.invoke('usuarios:listar',f),
    resumen:f=>ipcRenderer.invoke('usuarios:resumen',f),
    guardar:d=>ipcRenderer.invoke('usuarios:guardar',d),
    eliminar:d=>ipcRenderer.invoke('usuarios:eliminar',d),
    autenticar:d=>ipcRenderer.invoke('usuarios:autenticar',d),
    sesionActual:d=>ipcRenderer.invoke('usuarios:sesion_actual',d),
    cerrarSesion:d=>ipcRenderer.invoke('usuarios:cerrar_sesion',d),
    cambiarClave:d=>ipcRenderer.invoke('usuarios:cambiar_clave',d),
    restablecerClave:d=>ipcRenderer.invoke('usuarios:restablecer_clave',d)
  },
  monitoreo:{
    listar:d=>ipcRenderer.invoke('monitoreo:listar',d),
    vincular:d=>ipcRenderer.invoke('monitoreo:vincular',d),
    desvincular:d=>ipcRenderer.invoke('monitoreo:desvincular',d),
    historial:d=>ipcRenderer.invoke('monitoreo:historial',d)
  },
  sistema:{
    info:()=>ipcRenderer.invoke('sistema:info'),
    datosEjemplo:()=>ipcRenderer.invoke('sistema:datos_ejemplo'),
    limpiar:alcance=>ipcRenderer.invoke('sistema:limpiar',alcance),
    respaldo:()=>ipcRenderer.invoke('sistema:respaldo'),
    abrirCarpeta:()=>ipcRenderer.invoke('sistema:abrir_carpeta'),
    auditoria:f=>ipcRenderer.invoke('sistema:auditoria',f)
  }
});
